### ISSUE TITLE
No version specified, and no candidate version available for graphite-carbon

### ISSUE THREAD

**Issue by praste** [opscode-cookbooks/oc-graphite#4]
I get error `No version specified, and no candidate version available for graphite-carbon` while running 
`oc-graphite::graphite_carbon` recipe

**Comment by paulmooring** [comment]
Thanks for the issue, at present this cookbook only supports Ubuntu 14.04 (earlier versions do not provide a `graphite-carbon` package in the default repos).  I suspect your error is due to trying to run this against another platform.  Because this cookbook was create with only internal usage in mind, no attempts have been made to support other platforms.
